#!/bin/bash

echo "Dame un primer numero: "
read num1
echo "Dame un segundo numero: "
read num2


let total=$num1+$num2

echo "La suma de tus numeros es $total"

if [ $num1 -gt $num2 ]; then
        echo "Tu primer numero es mas grande"
else
        echo "Tu segundo numero es mas grande"
fi
