#!/bin/bash

#Introduccion de PIN
read -s -p "Introduce tu PIN: " pin1

echo -e "\nVariable 1 Almacenada."

read -s -p "Vuelve a introducir el PIN: " pin2

echo -e "\nVariable 2 Alamcenada."

if [ $pin1 -eq $pin2 ]; then
        echo "El PIN coincide."
else
        echo "El PIN no coincide."
fi

#Introduccion de Password

read -s -p "Introduce password: " pass1

read -s -p "Verifica password: " pass2

if [ $pass1 == $pass2 ]; then
        echo "El password coincide!"
else
        echo "No coincide el password!, bruto!!"
fi

#Finaliza el programa

echo "Gracias por usar el programa!"

